rules:

  - words: ["веб", "дизайн"]
    operator: AND
  - words: ["веб", "дизайн"]
    operator: OR

  - words: ["мобильный", "дизайн"]
    operator: AND
  - words: ["android", "разработчик"]
    operator: OR
  - words: [ "андроид", "разработчик" ]
    operator: AND

  - words: ["веб", "дизайнер"]
    operator: AND

  - words: [ "мобильный", "дизайнер" ]
    operator: AND

  - words: [ "дизайн", "интерфейсов" ]
    operator: AND
  - words: [ "дизайн", "интерфейсов" ]
    operator: AND
  - words: [ "веб", "дизайнер" ]
    operator: OR
  - words: [ "веб", "дизайнера" ]
    operator: OR
